import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  tutorialSidebar: [
    'intro',
    'deployment',
    {
      type: 'category',
      label: 'Algorithmen',
      items: [
        'algorithms/fundamentals-of-algorithms',
        'algorithms/basic-algorithms',
        'algorithms/algorithmic-problem-solving',
      ],
    },
    {
      type: 'category',
      label: 'Softwareentwicklung',
      items: [
        'software-development/software-types',
        'software-development/development-implementation-automation',
        'software-development/technical-legal-conditions',
      ],
    },
    {
      type: 'category',
      label: 'IT-Sicherheit',
      items: [
        'it-security/encryption',
        'it-security/iam',
        'it-security/network-security',
        'it-security/application-security',
        'it-security/risk-management',
      ],
    },
  ],
};

export default sidebars;
