import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  tutorialSidebar: [
    'intro',
    'deployment',
    {
      type: 'category',
      label: 'Projektmanagement',
      items: [
        'project-management/agile-software-development',
      ],
    },
    {
      type: 'category',
      label: 'OOP Programmierung',
      items: [
        'oop-programming/oop-intro',
      ],
    },
    {
      type: 'category',
      label: 'Algorithmen',
      items: [
        'algorithms/algorithms-intro',
        'algorithms/sorting-algorithms',
        'algorithms/searching-algorithms',
      ],
    },
    {
      type: 'category',
      label: 'IT-Sicherheit',
      items: [
        'it-security/encryption',
      ],
    },
    {
      type: 'category',
      label: 'Designpatterns',
      items: [
        'design-patterns/factory-pattern',
        'design-patterns/singleton-pattern',
      ],
    },
  ],
};

export default sidebars;
